"""new attribute on user

Revision ID: 140a51c3025c
Revises: 985fe712b7aa
Create Date: 2024-09-09 15:41:17.657067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '140a51c3025c'
down_revision = '985fe712b7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_artist', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1024), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('bio')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('is_artist')

    # ### end Alembic commands ###
