"""Add Post model

Revision ID: 985fe712b7aa
Revises: 97da0ae10778
Create Date: 2024-09-07 10:14:29.803743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '985fe712b7aa'
down_revision = '97da0ae10778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
